### ISSUE TITLE
sip doesn't build

### ISSUE THREAD

**Issue by isanae** [ModOrganizer2/modorganizer-umbrella#41]
The "make sip" task currently fails and `stdout.log` shows a bunch of "Cannot open include file: 'Python.h'". This broke last week because of the switch to python 3.7.3(4956a4fa37b3d67d296d8bb3850656e6d857a42f). That version introduced [a change](https://github.com/python/cpython/commit/4f6854a690e95ab5159687794652c639a020d6fd) meant to fix [a problem](https://bugs.python.org/issue35299) with `distutils.sysconfig.get_python_inc()`. Long story short, `get_python_inc()` now returns two paths combined with `;` instead of only one, which breaks `-I` in siplib/Makefile.

The real fix will have to come from sip, which still seems broken on 4.19.17, but the head seems to have switched to a different configuration script. In the meantime, siplib/Makefile can be manually fixed by changing `CPPFLAGS` and replacing the `;` with a space and `-I`.

(There's also a stray `logging.debug()` statement on unibuild/projects/sip.py:75)

**Comment by Silarn** [comment]
Yeah, this was a known issue, but thanks for documenting it.
